set(CTEST_PROJECT_NAME "IGSTK")
set(CTEST_NIGHTLY_START_TIME "23:59:59 EDT")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "www.cdash.org")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=igstk")
set(CTEST_DROP_SITE_CDASH TRUE)
