// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "/home/ozgur/workspace/IGSTKSandbox/Examples/FourViews/FourViews.h"

void FourViews::cb_QuitButton_i(Fl_Button*, void*) {
  this->Quit();
}
void FourViews::cb_QuitButton(Fl_Button* o, void* v) {
  ((FourViews*)(o->parent()->user_data()))->cb_QuitButton_i(o,v);
}

void FourViews::cb_Load_i(Fl_Button*, void*) {
  this->LoadVessels();
}
void FourViews::cb_Load(Fl_Button* o, void* v) {
  ((FourViews*)(o->parent()->user_data()))->cb_Load_i(o,v);
}

void FourViews::cb_Load1_i(Fl_Button*, void*) {
  this->LoadLiver();
}
void FourViews::cb_Load1(Fl_Button* o, void* v) {
  ((FourViews*)(o->parent()->user_data()))->cb_Load1_i(o,v);
}

void FourViews::cb_Move_i(Fl_Button*, void*) {
  this->MoveVessels();
}
void FourViews::cb_Move(Fl_Button* o, void* v) {
  ((FourViews*)(o->parent()->user_data()))->cb_Move_i(o,v);
}

FourViews::FourViews() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = mainWindow = new Fl_Double_Window(775, 710, "IGSTK: Four Quadrants Example");
    w = o;
    o->user_data((void*)(this));
    { igstk::FLTKWidget* o = Display3DWidget = new igstk::FLTKWidget(5, 5, 380, 330, "Display 3D");
      o->box(FL_FLAT_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BACKGROUND2_COLOR);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    { igstk::FLTKWidget* o = DisplayAxialWidget = new igstk::FLTKWidget(388, 5, 380, 330, "Display Axial");
      o->box(FL_FLAT_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BACKGROUND2_COLOR);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    { igstk::FLTKWidget* o = DisplaySagittalWidget = new igstk::FLTKWidget(388, 338, 380, 330, "Display Sagittal");
      o->box(FL_FLAT_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BACKGROUND2_COLOR);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    { igstk::FLTKWidget* o = DisplayCoronalWidget = new igstk::FLTKWidget(5, 338, 380, 330, "Display Coronal");
      o->box(FL_FLAT_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BACKGROUND2_COLOR);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    { Fl_Button* o = QuitButton = new Fl_Button(670, 675, 85, 25, "Quit");
      o->callback((Fl_Callback*)cb_QuitButton);
    }
    { Fl_Button* o = new Fl_Button(15, 680, 105, 25, "Load Vessels");
      o->callback((Fl_Callback*)cb_Load);
    }
    { Fl_Button* o = new Fl_Button(130, 680, 105, 25, "Load Liver");
      o->callback((Fl_Callback*)cb_Load1);
    }
    { Fl_Button* o = new Fl_Button(250, 680, 105, 25, "Move Vessels");
      o->callback((Fl_Callback*)cb_Move);
    }
    o->end();
    o->resizable(o);
  }
}

FourViews::~FourViews() {
  delete Display3DWidget;
delete DisplayAxialWidget;
delete DisplaySagittalWidget;
delete DisplayCoronalWidget;
}

void FourViews::Quit() {
  mainWindow->hide();
}

void FourViews::Show() {
  mainWindow->show();
}

void FourViews::LoadVessels() {
}

void FourViews::LoadLiver() {
}

void FourViews::MoveVessels() {
}
