// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef FourViews_h
#define FourViews_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <igstkFLTKWidget.h>
#include <FL/Fl_Button.H>

class FourViews {
public:
  FourViews();
  Fl_Double_Window *mainWindow;
  igstk::FLTKWidget *Display3DWidget;
  igstk::FLTKWidget *DisplayAxialWidget;
  igstk::FLTKWidget *DisplaySagittalWidget;
  igstk::FLTKWidget *DisplayCoronalWidget;
  Fl_Button *QuitButton;
private:
  void cb_QuitButton_i(Fl_Button*, void*);
  static void cb_QuitButton(Fl_Button*, void*);
  void cb_Load_i(Fl_Button*, void*);
  static void cb_Load(Fl_Button*, void*);
  void cb_Load1_i(Fl_Button*, void*);
  static void cb_Load1(Fl_Button*, void*);
  void cb_Move_i(Fl_Button*, void*);
  static void cb_Move(Fl_Button*, void*);
public:
  virtual ~FourViews();
  virtual void Quit();
  virtual void Show();
  virtual void LoadVessels();
  virtual void LoadLiver();
  virtual void MoveVessels();
};
#endif
