/*=========================================================================

  Program:   Image Guided Surgery Software Toolkit
  Module:    igstkQuadrantViews.h
  Language:  C++
  Date:      $Date$
  Version:   $Revision$

  Copyright (c) ISC  Insight Software Consortium.  All rights reserved.
  See IGSTKCopyright.txt or http://www.igstk.org/copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notices for more information.

=========================================================================*/

// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef __igstkQuadrantViews_h
#define __igstkQuadrantViews_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Slider.H>

#include "igstkFLTKWidget.h"
#include "igstkView2D.h"
#include "igstkView3D.h"
#include "igstkEvents.h"
#include "igstkCTImageSpatialObject.h"

namespace igstk {

class QuadrantViews : public Fl_Group {
public:

  QuadrantViews(int X, int Y, int W, int H, const char *L = 0);

  virtual ~QuadrantViews(void);

  typedef igstk::View          ViewType;
  typedef igstk::View2D        ViewType2D;
  typedef igstk::View3D        ViewType3D;

  ViewType2D::Pointer          m_DisplayAxial;
  ViewType2D::Pointer          m_DisplayCoronal;
  ViewType2D::Pointer          m_DisplaySagittal;
  ViewType3D::Pointer          m_Display3D;

  igstk::FLTKWidget * m_DisplayAxialWidget;
  igstk::FLTKWidget * m_DisplaySagittalWidget;
  igstk::FLTKWidget * m_DisplayCoronalWidget;
  igstk::FLTKWidget * m_Display3DWidget;

  Fl_Value_Slider * m_AxialSlider;
  Fl_Value_Slider * m_SagittalSlider;
  Fl_Value_Slider * m_CoronalSlider;

  std::vector< igstk::FLTKWidget * >   m_Displays;
  std::vector< ViewType::Pointer   >   m_Views;
  std::vector< Fl_Value_Slider   * >   m_Sliders;

  /** Event for reslicing from slider bar */
  typedef CTImageSpatialObject::IndexType  IndexType;

  igstkLoadedEventMacro( ReslicingEvent, IGSTKEvent, IndexType );

  unsigned long AddObserver( 
    const ::itk::EventObject & event, ::itk::Command * observer );

  void RemoveObserver( unsigned long tag );
  void RemoveAllObservers();

protected:

  virtual void RequestResliceImage(void);

private:

  // Call backs for slider bars
  void cb_AxialSlider_i(Fl_Value_Slider*, void*);
  static void cb_AxialSlider(Fl_Value_Slider*, void*);
  void cb_SagittalSlider_i(Fl_Value_Slider*, void*);
  static void cb_SagittalSlider(Fl_Value_Slider*, void*);
  void cb_CoronalSlider_i(Fl_Value_Slider*, void*);
  static void cb_CoronalSlider(Fl_Value_Slider*, void*);

  ::itk::Object::Pointer    m_Reporter;

};

} // end namespace igstk

#endif
