/*=========================================================================

  Program:   Image Guided Surgery Software Toolkit
  Module:    TrackerConfigurationExample.cxx
  Language:  C++
  Date:      $Date$
  Version:   $Revision$

  Copyright (c) ISC  Insight Software Consortium.  All rights reserved.
  See IGSTKCopyright.txt or http://www.igstk.org/copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notices for more information.

=========================================================================*/
#if defined(_MSC_VER)
//  Warning about: identifier was truncated to '255' characters 
//  in the debug information (MVC6.0 Debug)
#pragma warning( disable : 4284 )
#endif

#include "igstkTrackerConfiguration.h"
#include "igstkTrackerController.h"
#include "igstkTrackerConfigurationFileReader.h"
#include "igstkPolarisVicraConfigurationXMLFileReader.h"
#include "igstkPolarisSpectraConfigurationXMLFileReader.h"
#include "igstkPolarisHybridConfigurationXMLFileReader.h"
#include "igstkAuroraConfigurationXMLFileReader.h"
#include "igstkMicronConfigurationXMLFileReader.h"
#include "igstkAscensionConfigurationXMLFileReader.h"

/**
 * Observer for the event generated by 
 * TrackerConfigurationFileReader->RequestGetData() method.
 */
igstkObserverObjectMacro( 
  TrackerConfiguration, 
  igstk::TrackerConfigurationFileReader::TrackerConfigurationDataEvent,
  igstk::TrackerConfiguration )

/**
 * Observer for the TrackerController->RequestInitialize() failure.
 */
igstkObserverMacro( InitializeError, 
                    igstk::TrackerController::InitializeErrorEvent, 
                    std::string )
                   
/**
 * This program receives a tracker's xml configuration file, and attempts to
 * read it. If it is one of the supported trackers and the xml file is valid
 * a tracker controller is initialized (tracker is implicitly initialized too).
 */
int main( int argc, char *argv[] )
{
  if( argc != 2 )
    {
      std::cerr<<"Wrong number of input arguments.\n";
      std::cerr<<"Usage: "<<argv[0]<<" tracker_configuration_file_name\n";
      return EXIT_FAILURE;
    }


  const unsigned int NUM_TRACKER_TYPES = 6;
  igstk::TrackerConfigurationXMLFileReaderBase::Pointer 
    trackerCofigurationXMLReaders[NUM_TRACKER_TYPES];
  trackerCofigurationXMLReaders[0] = 
    igstk::PolarisVicraConfigurationXMLFileReader::New();
  trackerCofigurationXMLReaders[1] = 
    igstk::PolarisSpectraConfigurationXMLFileReader::New();
  trackerCofigurationXMLReaders[2] = 
    igstk::PolarisHybridConfigurationXMLFileReader::New();
  trackerCofigurationXMLReaders[3] = 
    igstk::AuroraConfigurationXMLFileReader::New();
  trackerCofigurationXMLReaders[4] = 
    igstk::MicronConfigurationXMLFileReader::New();
  trackerCofigurationXMLReaders[5] =
       igstk::AscensionConfigurationXMLFileReader::New();


  igstk::TrackerConfigurationFileReader::Pointer trackerConfigReader = 
    igstk::TrackerConfigurationFileReader::New();

                //need to observe if the request read succeeds or fails
                //there is a third option that the read is invalid, if the
                //file name or xml reader weren't set
  igstk::TrackerConfigurationFileReader::ReadFailSuccessObserver::Pointer rfso = 
    igstk::TrackerConfigurationFileReader::ReadFailSuccessObserver::New();
  trackerConfigReader->AddObserver( 
    igstk::TrackerConfigurationFileReader::ReadSuccessEvent(),
    rfso );
  trackerConfigReader->AddObserver( 
    igstk::TrackerConfigurationFileReader::ReadFailureEvent(),
    rfso );
  trackerConfigReader->AddObserver( 
    igstk::TrackerConfigurationFileReader::UnexpectedTrackerTypeEvent(),
    rfso );

             //setting the file name and reader always succeeds so I don't
             //observe for success event
  trackerConfigReader->RequestSetFileName( argv[1] );

  TrackerConfigurationObserver::Pointer tco = 
    TrackerConfigurationObserver::New();
  const igstk::TrackerConfiguration *trackerConfiguration = NULL;

           //attempt reading with all readers till one succeeds
  for( unsigned int i=0; 
       trackerConfiguration == NULL && i<NUM_TRACKER_TYPES; 
       i++ )
    {
    //setting the xml reader always succeeds so I don't
    //observe the success event
    trackerConfigReader->RequestSetReader( trackerCofigurationXMLReaders[i] );  
 
    //try to read using the current xml reader
    trackerConfigReader->RequestRead();

    //check what happened
    if( rfso->GotUnexpectedTrackerType() )
    {
      rfso->Reset();
    }
    else if( rfso->GotFailure() && !rfso->GotUnexpectedTrackerType() )
    {
      std::cerr<<"Failed reading configuration file (";
      std::cerr<<rfso->GetFailureMessage()<<").\n";
      return EXIT_FAILURE;
    }
    else if( rfso->GotSuccess() )
      {
      //get the configuration data from the reader
      trackerConfigReader->AddObserver( 
        igstk::TrackerConfigurationFileReader::TrackerConfigurationDataEvent(),
        tco );
      trackerConfigReader->RequestGetData();

      if( tco->GotTrackerConfiguration() )
        {
        trackerConfiguration = tco->GetTrackerConfiguration();        
        }
      }
    }
    
  if( trackerConfiguration == NULL )   
    {
    std::cerr<<"Unsupported tracker type.\n";
    return EXIT_FAILURE;
    }
  
  
  //initialize the tracker controller
  igstk::TrackerController::Pointer trackerController = 
    igstk::TrackerController::New();
  
  InitializeErrorObserver::Pointer ieo = 
    InitializeErrorObserver::New();
  trackerController->AddObserver( 
     igstk::TrackerController::InitializeErrorEvent(), ieo );
  trackerController->RequestInitialize( trackerConfiguration );
  if( ieo->GotInitializeError() )
    {
    std::cout<<ieo->GetInitializeError()<<"\n";
    return EXIT_FAILURE;
    }

  return EXIT_SUCCESS;
}

